- name: Run Windows Server Updates
  hosts: all
  connection: winrm

  tasks:
  - name: Install all security updates aith reboots
    win_file:
       path: c:\temp\folder\subfolder1
       state: directory
  - name: Install all security, critical, and rollup updates
    win_updates:
     category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
